name: codehatch
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^15.1.3
  google_fonts: ^6.2.1
  intl: ^0.20.2
  cached_network_image: ^3.4.1
  provider: ^6.1.5
  wolt_modal_sheet: ^0.11.0
  firebase_core: ^3.14.0
  cloud_firestore: ^5.6.9
  collection: ^1.19.1
  firebase_auth: ^5.6.0
  shared_preferences: ^2.5.3
  toastification: ^3.0.3
  flutter_svg: ^2.2.0
  country_picker: ^2.0.27
  share_plus: ^11.0.0
  easy_localization: ^3.0.7+1
  flutter_staggered_grid_view: ^0.7.0
  haptic_feedback: ^0.5.1+1
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.5.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/translations/
    - assets/icon/

